name: e_commerence
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

#--------------- dependency------------------
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.0
  lottie: ^3.3.1
  smooth_page_indicator: ^1.2.1
  get: ^4.7.2
  get_storage: ^2.1.1
  iconsax: ^0.0.8
  carousel_slider: ^5.1.1
  readmore: ^3.0.0



  #firebase
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  cloud_firestore: ^6.0.1
  google_sign_in: ^7.1.1

#------------------------------------------


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0



flutter:

  uses-material-design: true

  #----------------- assets-----------------------
  assets:
    - assets/logo/
    - assets/images/
    - assets/fonts/
    - assets/animation/
    - assets/icons/category/
    - assets/icons/payment_methods/
    - assets/banners/
    - assets/products/
    - assets/brands/



  #------------------------------ fonts-----------------
  fonts:
    - family: 'Nunito'
      fonts:
        - asset: assets/fonts/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 800
        - asset: assets/fonts/Nunito-Italic.ttf
          style: italic
        - asset: assets/fonts/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/Nunito-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Nunito-SemiBold.ttf
          weight: 600

  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
